### ISSUE TITLE
Dropping a shape sometimes changes the color and shape of adjacent shapes

### ISSUE THREAD

**Issue by FuzzyBoots** [amishne/mipui#218] opened 2018-12-27 20:12 UTC
This is happening when placing adjacent shapes. A common visual bug that happens is that placing a shape in an adjacent square to an existing shape visually changes that shape's color and/or shape until you move away. Sometimes, it actually changes the color and/or shape. Hitting Ctrl-Z to undo undoes the placement entirely, so I don't think it's a matter of accidentally double-clicking. When this does happen, it happens consistently for a while.

Every once in a while, I've experienced the situation where just changing the color or shape in the menu changes a token on the map, generally the last one I edited.

I can't trigger either of the issues at the moment, but I was getting it about a half hour ago.

**Comment by amishne** [comment] 2019-08-09 03:15
Duplicate of #222

**Closed by amishne** 2019-08-09 03:15 UTC
